# Exact updated-goal column order and empty type prototypes. No measurements.
output_schema <-
list(nerve_object_distances_to_tumor_stroma_border = structure(list(
    nerve_object_id = character(0), image_id = character(0), 
    StudyID = character(0), subtype_code = integer(0), subtype_label = character(0), 
    local_id = integer(0), centroid_x_px = numeric(0), centroid_y_px = numeric(0), 
    area_px = integer(0), area_um2 = numeric(0), dist_nearest_tumor_stroma_border_um = numeric(0), 
    nearest_tumor_stroma_border_segment_length_um = numeric(0), 
    dist_longest_tumor_stroma_border_um = numeric(0), longest_tumor_stroma_border_segment_length_um = numeric(0), 
    dist_nearest_stroma_glass_border_um = numeric(0), nearest_stroma_glass_border_segment_length_um = numeric(0), 
    dist_longest_stroma_glass_border_um = numeric(0), longest_stroma_glass_border_segment_length_um = numeric(0), 
    keep_or_exclude = character(0), include_image_final_spatial_cohort = logical(0), 
    reason_exclude_final_spatial_cohort = character(0)), row.names = integer(0), class = "data.frame"), 
    nerve_vessel_area_by_distance_to_tumor_stroma_border = structure(list(
        image_id = character(0), reference_name = character(0), 
        band_index = integer(0), band_label = character(0), band_inner_um = integer(0), 
        band_outer_um = numeric(0), layer_name = character(0), 
        subtype_code = integer(0), subtype_label = character(0), 
        area_px = integer(0), area_um2 = numeric(0), stroma_area_um2 = numeric(0), 
        proportion_object_area_per_band = numeric(0), include_image_final_spatial_cohort = logical(0), 
        reason_exclude_final_spatial_cohort = character(0)), row.names = integer(0), class = "data.frame"), 
    vessel_object_distances_to_tumor_stroma_border = structure(list(
        vessel_object_id = character(0), image_id = character(0), 
        StudyID = character(0), subtype_label = character(0), 
        local_id = integer(0), centroid_x_px = numeric(0), centroid_y_px = numeric(0), 
        area_px = integer(0), area_um2 = numeric(0), dist_nearest_tumor_stroma_border_um = numeric(0), 
        nearest_tumor_stroma_border_segment_length_um = numeric(0), 
        dist_longest_tumor_stroma_border_um = numeric(0), longest_tumor_stroma_border_segment_length_um = numeric(0), 
        dist_nearest_stroma_glass_border_um = numeric(0), nearest_stroma_glass_border_segment_length_um = numeric(0), 
        dist_longest_stroma_glass_border_um = numeric(0), longest_stroma_glass_border_segment_length_um = numeric(0), 
        object_id = integer(0), s.area = integer(0), s.perimeter = integer(0), 
        s.radius.mean = numeric(0), s.radius.sd = numeric(0), 
        s.radius.min = numeric(0), s.radius.max = numeric(0), 
        circularity = numeric(0), pa_ratio = numeric(0), radius_cv = numeric(0), 
        roundness = numeric(0), eccentricity = numeric(0), pa_ecc_ratio = numeric(0), 
        edge_granularity = numeric(0), smoothness = numeric(0), 
        branch_count = integer(0), lumen_fraction = numeric(0), 
        solidity = numeric(0), keep_or_exclude = character(0), 
        include_image_final_spatial_cohort = logical(0), reason_exclude_final_spatial_cohort = character(0)), row.names = integer(0), class = "data.frame"))
