#!/usr/bin/env Rscript
# Goal tables are used only for post-computation verification, never image processing.
# This copies only the three specified metric CSVs; artifacts stay in RUN_DIR.
local({
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) != 3L) stop('Usage: Rscript R/verify_and_publish.R RUN_DIR UPDATED_GOAL_DIR TABLES_DIR')
  script <- sub('^--file=', '', grep('^--file=', commandArgs(), value = TRUE)[1])
  root <- normalizePath(file.path(dirname(script), '..'))
  source(file.path(root, 'R/output_schema.R'), local = TRUE)
  run <- normalizePath(args[1], mustWork = TRUE)
  reference <- normalizePath(args[2], mustWork = TRUE)
  tables <- normalizePath(args[3], mustWork = TRUE)
  filenames <- paste0(names(output_schema), '.csv')
  from <- file.path(run, filenames)
  to <- file.path(tables, filenames)
  if (any(file.exists(to))) stop('Destination tables already exist; preserve them before publishing a replacement.')
  if (!file.exists(file.path(run, 'COMPLETE.txt'))) stop('Run has no execution-complete marker.')
  before <- tools::md5sum(from)
  if (anyNA(before)) stop('Cannot hash every output table.')
  status <- system2(file.path(R.home('bin'), 'Rscript'), shQuote(c(file.path(root, 'R/validate_outputs.R'), run, reference)))
  if (status != 0L) stop('Validation failed: no tables were published.')
  if (!identical(before, tools::md5sum(from))) stop('Tables changed during validation; nothing published.')
  if (!all(file.copy(from, to, overwrite = FALSE))) stop('Copy failed; publication is incomplete.')
  copied <- tools::md5sum(to)
  if (!identical(unname(before), unname(copied))) stop('Copied table checksums differ.')
  write.csv(data.frame(file = filenames, md5 = unname(copied)), file.path(run, 'validation/published_tables_md5.csv'), row.names = FALSE)
  writeLines(c(paste('Published to', tables), paste('Images:', length(readLines(file.path(run, 'image_ids.txt')))), 'Only the requested image subset was validated; consult image_ids.txt.', filenames), file.path(run, 'validation/PUBLISHED.txt'))
  cat('PASS: all three validated tables copied and checksums verified.\n')
})
